name: Release to NuGet

on:
  release:
    types: [published]
    
env:
  PROJECT_PATH: SpanParseForStandard/SpanParseForStandard.csproj
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build --project $PROJECT_PATH -c Release
    - name: Test
      run: dotnet test --project $PROJECT_PATH -c Release --no-build
    - name: Pack nugets
      run: dotnet pack --project $PROJECT_PATH -c Release --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json